In [20]:
import pandas as pd

In [21]:
freddie_mae = pd.read_parquet(
    "../../01_original_data/Freddie_Mae_2025Q1.parquet", engine="pyarrow"
)
freddie_mae.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388622 entries, 0 to 388621
Columns: 110 entries, 0 to 109
dtypes: float64(75), int64(14), object(21)
memory usage: 326.1+ MB

In [22]:
freddie_mae.head()

,0,1,2,3,4,5,6,7,8,9,...,100,101,102,103,104,105,106,107,108,109
0,NaN,139435503,12025,C,"JPMorgan Chase Bank, National Association","JPMorgan Chase Bank, NA",NaN,6.625,6.625,282000.0,...,NaN,7,N,NaN,None,7,NaN,NaN,7,NaN
1,NaN,139435503,22025,C,"JPMorgan Chase Bank, National Association","JPMorgan Chase Bank, NA",NaN,6.625,6.625,282000.0,...,NaN,7,N,NaN,None,7,NaN,NaN,7,NaN
2,NaN,139435503,32025,C,"JPMorgan Chase Bank, National Association","JPMorgan Chase Bank, NA",NaN,6.625,6.625,282000.0,...,NaN,7,N,NaN,None,7,NaN,NaN,7,NaN
3,NaN,139435504,12025,R,Other,Other,NaN,6.250,6.250,176000.0,...,NaN,7,N,NaN,None,7,NaN,NaN,7,NaN
4,NaN,139435504,22025,R,Other,Other,NaN,6.250,6.250,176000.0,...,NaN,7,N,NaN,None,7,NaN,NaN,7,NaN

In [23]:
# Remove columns that are completely null
print(f"The shape of the dataset is: {freddie_mae.shape}")
total_nulls = freddie_mae.isna().sum()
total_no_of_rows = len(freddie_mae)
for column, null_count in total_nulls.items():
    if null_count == total_no_of_rows:
        freddie_mae = freddie_mae.rename(columns={column: "delete"})

freddie_mae_clean = freddie_mae.drop(columns=["delete"])
print(f"The shape of the cleaned dataset is: {freddie_mae_clean.shape}")

The shape of the dataset is: (388622, 110)
The shape of the cleaned dataset is: (388622, 52)

In [24]:
freddie_mae_clean.head()

,1,2,3,4,5,7,8,9,11,12,...,73,78,80,85,86,101,102,104,105,108
0,139435503,12025,C,"JPMorgan Chase Bank, National Association","JPMorgan Chase Bank, NA",6.625,6.625,282000.0,282000.0,360,...,N,7,N,A,N,7,N,None,7,7
1,139435503,22025,C,"JPMorgan Chase Bank, National Association","JPMorgan Chase Bank, NA",6.625,6.625,282000.0,282000.0,360,...,N,7,N,A,N,7,N,None,7,7
2,139435503,32025,C,"JPMorgan Chase Bank, National Association","JPMorgan Chase Bank, NA",6.625,6.625,282000.0,281000.0,360,...,N,7,N,A,N,7,N,None,7,7
3,139435504,12025,R,Other,Other,6.250,6.250,176000.0,176000.0,360,...,N,7,N,A,N,7,N,None,7,7
4,139435504,22025,R,Other,Other,6.250,6.250,176000.0,176000.0,360,...,N,7,N,A,N,7,N,None,7,7

In [25]:
# Rename columns based on data dictionary
freddie_mae_clean = freddie_mae_clean.rename(
    columns={
        "1": "reference_pool_id",
        "2": "monthly_reporting_period",
        "3": "channel",
        "4": "seller_name",
        "5": "servicer_name",
        "7": "original_interest_rate",
        "8": "current_interest_rate",
        "9": "upb_at_issuance",
        "11": "current_actual_upb",
        "12": "original_loan_term",
        "13": "origination_date",
        "14": "first_payment_date",
        "15": "loan_age",
        "16": "remaining_months_to_legal_maturity",
        "17": "remaining_months_to_maturity",
        "18": "maturity_date",
        "19": "original_loan_to_value_ltv",
        "20": "original_combined_loan_to_value_cltv",
        "21": "number_of_borrowers",
        "22": "debt_to_income_dti",
        "23": "borrower_credit_score_at_origination",
        "24": "co_borrower_credit_score_at_origination",
        "25": "first_time_home_buyer_indicator",
        "26": "loan_purpose",
        "27": "property_type",
        "28": "number_of_units",
        "29": "occupancy_status",
        "30": "property_state",
        "31": "metropolitan_statistical_area_msa",
        "32": "zip_code_short",
        "33": "mortgage_insurance_percentage",
        "34": "amortization_type",
        "35": "prepayment_penalty_indicator",
        "36": "interest_only_loan_indicator",
        "39": "current_loan_delinquency_status",
        "40": "loan_payment_history",
        "41": "modification_flag",
    }
)

In [26]:
freddie_mae_clean.head(20)
# freddie_mae_clean[43]

,reference_pool_id,monthly_reporting_period,channel,seller_name,servicer_name,original_interest_rate,current_interest_rate,upb_at_issuance,current_actual_upb,original_loan_term,...,73,78,80,85,86,101,102,104,105,108
0,139435503,12025,C,"JPMorgan Chase Bank, National Association","JPMorgan Chase Bank, NA",6.625,6.625,282000.0,282000.0,360,...,N,7,N,A,N,7,N,None,7,7
1,139435503,22025,C,"JPMorgan Chase Bank, National Association","JPMorgan Chase Bank, NA",6.625,6.625,282000.0,282000.0,360,...,N,7,N,A,N,7,N,None,7,7
2,139435503,32025,C,"JPMorgan Chase Bank, National Association","JPMorgan Chase Bank, NA",6.625,6.625,282000.0,281000.0,360,...,N,7,N,A,N,7,N,None,7,7
3,139435504,12025,R,Other,Other,6.250,6.250,176000.0,176000.0,360,...,N,7,N,A,N,7,N,None,7,7
4,139435504,22025,R,Other,Other,6.250,6.250,176000.0,176000.0,360,...,N,7,N,A,N,7,N,None,7,7
5,139435504,32025,R,Other,Other,6.250,6.250,176000.0,176000.0,360,...,N,7,N,A,N,7,N,None,7,7
6,139435505,12025,B,NewRez LLC,New Residential Mortgage LLC,6.125,6.125,140000.0,140000.0,360,...,N,H,N,A,N,7,N,None,7,7
7,139435505,22025,B,NewRez LLC,New Residential Mortgage LLC,6.125,6.125,140000.0,140000.0,360,...,N,H,N,A,N,7,N,None,7,7
8,139435505,32025,B,NewRez LLC,New Residential Mortgage LLC,6.125,6.125,140000.0,140000.0,360,...,N,H,N,A,N,7,N,None,7,7
9,139435506,12025,R,Other,Other,7.125,7.125,80000.0,80000.0,180,...,N,7,N,A,N,7,N,None,7,7
10,139435506,22025,R,Other,Other,7.125,7.125,80000.0,80000.0,180,...,N,7,N,A,N,7,N,None,7,7
11,139435506,32025,R,Other,Other,7.125,7.125,80000.0,79000.0,180,...,N,7,N,A,N,7,N,None,7,7
12,139435507,12025,B,"Rocket Mortgage, LLC","Rocket Mortgage, LLC",5.750,5.750,803000.0,803000.0,180,...,N,7,N,A,N,7,N,None,7,7
13,139435507,22025,B,"Rocket Mortgage, LLC","Rocket Mortgage, LLC",5.750,5.750,803000.0,800000.0,180,...,N,7,N,A,N,7,N,None,7,7
14,139435507,32025,B,"Rocket Mortgage, LLC","Rocket Mortgage, LLC",5.750,5.750,803000.0,797000.0,180,...,N,7,N,A,N,7,N,None,7,7
15,139435508,12025,B,"United Wholesale Mortgage, LLC","United Wholesale Mortgage, LLC",5.852,5.852,314000.0,313000.0,180,...,N,7,N,A,N,7,N,None,7,7
16,139435508,22025,B,"United Wholesale Mortgage, LLC","United Wholesale Mortgage, LLC",5.852,5.852,314000.0,313000.0,180,...,N,7,N,A,N,7,N,None,7,7
17,139435508,32025,B,"United Wholesale Mortgage, LLC","United Wholesale Mortgage, LLC",5.852,5.852,314000.0,311000.0,180,...,N,7,N,A,N,7,N,None,7,7
18,139435509,12025,R,Other,PHH Mortgage Corporation,6.375,6.375,340000.0,340000.0,360,...,N,7,N,W,N,7,N,None,7,7
19,139435509,22025,R,Other,PHH Mortgage Corporation,6.375,6.375,340000.0,340000.0,360,...,N,7,N,W,N,7,N,None,7,7

In [27]:
freddie_mae_clean.to_parquet(
    "../../02_processed_data/freddie_mae_clean.parquet", index=False
)