In [2]:
import pandas as pd
from pathlib import Path

In [3]:
df = pd.read_csv("/Users/ramilmammadov/Desktop/Capstone Project/GitHub Repo/Capstone_Citizensbank_climate-risk_insurance-exposure_monitoring/02_processed_data/wildfire_data.csv")
df

       FIPS_CODE  FIRE_YEAR  FIRE_FREQUENCY  TOTAL_FIRE_SIZE STATE
0           1001       2003              43            274.8    AL
1           1001       2004              86            744.5    AL
2           1001       2005              63            234.2    AL
3           1001       2006              62            534.7    AL
4           1001       2007              93            477.3    AL
...          ...        ...             ...              ...   ...
41955      72147       2016              17             51.8    PR
41956      72147       2017               3             30.0    PR
41957      72147       2018              21             81.0    PR
41958      72147       2019              15            153.3    PR
41959      72147       2020              11             20.5    PR

[41960 rows x 5 columns]

In [4]:
INPUT = Path("/Users/ramilmammadov/Desktop/Capstone Project/GitHub Repo/Capstone_Citizensbank_climate-risk_insurance-exposure_monitoring/02_processed_data/wildfire_data.csv")           
OUTPUT = Path("/Users/ramilmammadov/Desktop/Capstone Project/GitHub Repo/Capstone_Citizensbank_climate-risk_insurance-exposure_monitoring/02_processed_data/wildfire_data_preprocessed.csv")

rename_map = {
    "FIPS_CODE": "FIPS",
    "FIRE_YEAR": "Year",
    "STATE": "State",
}

df = pd.read_csv(INPUT)
existing = {old: new for old, new in rename_map.items() if old in df.columns}
missing = [old for old in rename_map if old not in df.columns]

df = df.rename(columns=existing)
df.to_csv(OUTPUT, index=False)

print(f"Saved: {OUTPUT}")
print("Renamed:", ", ".join(f"{k}→{v}" for k, v in existing.items()) or "None")
if missing:
    print("Columns not found in the file:", ", ".join(missing))

df

Saved: /Users/ramilmammadov/Desktop/Capstone Project/GitHub Repo/Capstone_Citizensbank_climate-risk_insurance-exposure_monitoring/02_processed_data/wildfire_data_preprocessed.csv
Renamed: FIPS_CODE→FIPS, FIRE_YEAR→Year, STATE→State

        FIPS  Year  FIRE_FREQUENCY  TOTAL_FIRE_SIZE State
0       1001  2003              43            274.8    AL
1       1001  2004              86            744.5    AL
2       1001  2005              63            234.2    AL
3       1001  2006              62            534.7    AL
4       1001  2007              93            477.3    AL
...      ...   ...             ...              ...   ...
41955  72147  2016              17             51.8    PR
41956  72147  2017               3             30.0    PR
41957  72147  2018              21             81.0    PR
41958  72147  2019              15            153.3    PR
41959  72147  2020              11             20.5    PR

[41960 rows x 5 columns]